FROM python:3
# Set working directory to /usr/src/app 
WORKDIR .
# Copy the contents of the current local directory into the container's working directory 
ADD hello.py /
# Run a command
CMD ["python", "hello.py"]